# Copyright 2016-2023, Jarsa Sistemas, S.A. de C.V.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    "name": "Freight Management",
    "version": "15.0.2.0.5",
    "category": "Transport",
    "author": "Jarsa",
    "website": "https://www.jarsa.com.mx/page/transport-management-system",
    "depends": [
        "fleet",
        "hr",
        "account",
    ],
    "summary": "Management System for Carriers, Trucking and other companies",
    "license": "LGPL-3",
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/tms_travel_stage_data.xml",
        "views/hr_employee_driver_license_view.xml",
        "views/hr_employee_view.xml",
        "views/fleet_vehicle_insurance_view.xml",
        "views/fleet_vehicle_view.xml",
        "views/res_config_settings_view.xml",
        "views/tms_fuel_view.xml",
        "views/product_template_view.xml",
        "views/tms_advance_view.xml",
        "views/tms_expense_view.xml",
        "views/tms_factor_view.xml",
        "views/tms_route_view.xml",
        "views/tms_transportable_view.xml",
        "views/tms_travel_view.xml",
        "views/tms_travel_stage_view.xml",
        "views/tms_unit_kit_view.xml",
        "views/tms_waybill_view.xml",
        "data/product_product_data.xml",
        "data/decimal_precision_data.xml",
        "views/tms_view.xml",
        "views/account_move_view.xml",
    ],
    "demo": [
        "demo/account_account.xml",
        "demo/account_journal.xml",
        "demo/res_company.xml",
        "demo/res_partner.xml",
        "demo/product_product.xml",
        "demo/product_template.xml",
        "demo/fleet_vehicle_odometer.xml",
        "demo/fleet_vehicle_model_brand.xml",
        "demo/fleet_vehicle.xml",
        "demo/fleet_vehicle_insurance.xml",
        "demo/hr_employee.xml",
        "demo/hr_employee_driver_license.xml",
        "demo/tms_route.xml",
        "demo/tms_factor.xml",
        "demo/tms_travel.xml",
        "demo/tms_fuel.xml",
        "demo/tms_advance.xml",
        "demo/tms_transportable.xml",
        "demo/tms_unit_kit.xml",
        "demo/tms_waybill.xml",
        "demo/tms_waybill_transportable_line.xml",
    ],
    "application": True,
    "installable": True,
}
